select
	m.match_id ,
	s.step_number,
    p.roleindex,
    p.goal_value,
	IF(LOCATE('CONTROL RED',state) > 0, 1, -1),   
	IF(LOCATE('CONTROL WHITE',state) > 0, 1, -1), 
	IF(LOCATE('CELL 1 1 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 1 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 1 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 2 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 2 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 2 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 3 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 3 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 3 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 4 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 4 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 4 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 5 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 5 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 5 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 6 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 6 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 1 6 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 2 1 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 1 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 1 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 2 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 2 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 2 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 3 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 3 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 3 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 4 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 4 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 4 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 5 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 5 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 5 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 6 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 6 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 2 6 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 1 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 1 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 1 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 2 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 2 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 2 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 3 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 3 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 3 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 4 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 4 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 4 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 5 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 5 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 5 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 6 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 6 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 3 6 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 1 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 1 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 1 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 2 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 2 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 2 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 3 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 3 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 3 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 4 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 4 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 4 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 5 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 5 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 5 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 6 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 6 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 4 6 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 5 1 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 1 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 1 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 2 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 2 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 2 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 3 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 3 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 3 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 4 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 4 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 4 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 5 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 5 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 5 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 6 B',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 6 R',state) > 0, 1, -1),  
	IF(LOCATE('CELL 5 6 W',state) > 0, 1, -1),  
	IF(LOCATE('CELL 6 1 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 1 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 1 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 2 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 2 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 2 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 3 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 3 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 3 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 4 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 4 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 4 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 5 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 5 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 5 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 6 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 6 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 6 6 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 1 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 1 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 1 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 2 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 2 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 2 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 3 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 3 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 3 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 4 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 4 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 4 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 5 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 5 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 5 W',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 6 B',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 6 R',state) > 0, 1, -1),    
	IF(LOCATE('CELL 7 6 W',state) > 0, 1, -1),    
	locate('NOOP', move),
    locate('(DROP 1)', move),
    locate('(DROP 2)', move),
    locate('(DROP 3)', move),
    locate('(DROP 4)', move),
    locate('(DROP 5)', move),
    locate('(DROP 6)', move),
    locate('(DROP 7)', move)
FROM 
    states s, 
    matches m, 
    match_players p,
    moves mo
where 
    m.match_id = s.match_id and
    p.match_id = m.match_id and
    p.match_id = m.match_id and
    p.roleindex = mo.roleindex and
    mo.roleindex = p.roleindex and
    mo.match_id = m.match_id and
    mo.step_number = s.step_number and

    m.game = 'connect4' and 
    p.player != 'Random' #and
    #mo.move != 'NOOP' and
    #p.roleindex = 0

INTO OUTFILE 'connect4_big.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';