select 
	m.match_id ,
	s.step_number,
    p.roleindex,
    p.goal_value,
	IF(LOCATE('CONTROL BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CONTROL GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CONTROL MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CONTROL RED',state) > 0, 1, -1), 
	IF(LOCATE('CONTROL TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CONTROL YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('STEP 1',state) > 0, 1, -1), 
	IF(LOCATE('STEP 2',state) > 0, 1, -1), 
	IF(LOCATE('STEP 3',state) > 0, 1, -1), 
	IF(LOCATE('STEP 4',state) > 0, 1, -1), 
	IF(LOCATE('STEP 5',state) > 0, 1, -1), 
	IF(LOCATE('STEP 6',state) > 0, 1, -1), 
	IF(LOCATE('STEP 7',state) > 0, 1, -1), 
	IF(LOCATE('STEP 8',state) > 0, 1, -1), 
	IF(LOCATE('STEP 9',state) > 0, 1, -1), 
	IF(LOCATE('STEP 10',state) > 0, 1, -1), 
	IF(LOCATE('STEP 11',state) > 0, 1, -1), 
	IF(LOCATE('STEP 12',state) > 0, 1, -1), 
	IF(LOCATE('STEP 13',state) > 0, 1, -1), 
	IF(LOCATE('STEP 14',state) > 0, 1, -1), 
	IF(LOCATE('STEP 15',state) > 0, 1, -1), 
	IF(LOCATE('STEP 16',state) > 0, 1, -1), 
	IF(LOCATE('STEP 17',state) > 0, 1, -1), 
	IF(LOCATE('STEP 18',state) > 0, 1, -1), 
	IF(LOCATE('STEP 19',state) > 0, 1, -1), 
	IF(LOCATE('STEP 20',state) > 0, 1, -1), 
	IF(LOCATE('STEP 21',state) > 0, 1, -1), 
	IF(LOCATE('STEP 22',state) > 0, 1, -1), 
	IF(LOCATE('STEP 23',state) > 0, 1, -1), 
	IF(LOCATE('STEP 24',state) > 0, 1, -1), 
	IF(LOCATE('STEP 25',state) > 0, 1, -1), 
	IF(LOCATE('STEP 26',state) > 0, 1, -1), 
	IF(LOCATE('STEP 27',state) > 0, 1, -1), 
	IF(LOCATE('STEP 28',state) > 0, 1, -1), 
	IF(LOCATE('STEP 29',state) > 0, 1, -1), 
	IF(LOCATE('STEP 30',state) > 0, 1, -1), 
	IF(LOCATE('STEP 31',state) > 0, 1, -1), 
	IF(LOCATE('STEP 32',state) > 0, 1, -1), 
	IF(LOCATE('STEP 33',state) > 0, 1, -1), 
	IF(LOCATE('STEP 34',state) > 0, 1, -1), 
	IF(LOCATE('STEP 35',state) > 0, 1, -1), 
	IF(LOCATE('STEP 36',state) > 0, 1, -1), 
	IF(LOCATE('STEP 37',state) > 0, 1, -1), 
	IF(LOCATE('STEP 38',state) > 0, 1, -1), 
	IF(LOCATE('STEP 39',state) > 0, 1, -1), 
	IF(LOCATE('STEP 40',state) > 0, 1, -1), 
	IF(LOCATE('STEP 41',state) > 0, 1, -1), 
	IF(LOCATE('STEP 42',state) > 0, 1, -1), 
	IF(LOCATE('STEP 43',state) > 0, 1, -1), 
	IF(LOCATE('STEP 44',state) > 0, 1, -1), 
	IF(LOCATE('STEP 45',state) > 0, 1, -1), 
	IF(LOCATE('STEP 46',state) > 0, 1, -1), 
	IF(LOCATE('STEP 47',state) > 0, 1, -1), 
	IF(LOCATE('STEP 48',state) > 0, 1, -1), 
	IF(LOCATE('STEP 49',state) > 0, 1, -1), 
	IF(LOCATE('STEP 50',state) > 0, 1, -1), 
	IF(LOCATE('STEP 51',state) > 0, 1, -1), 
	IF(LOCATE('STEP 52',state) > 0, 1, -1), 
	IF(LOCATE('STEP 53',state) > 0, 1, -1), 
	IF(LOCATE('STEP 54',state) > 0, 1, -1), 
	IF(LOCATE('STEP 55',state) > 0, 1, -1), 
	IF(LOCATE('STEP 56',state) > 0, 1, -1), 
	IF(LOCATE('STEP 57',state) > 0, 1, -1), 
	IF(LOCATE('STEP 58',state) > 0, 1, -1), 
	IF(LOCATE('STEP 59',state) > 0, 1, -1), 
	IF(LOCATE('STEP 60',state) > 0, 1, -1), 
	IF(LOCATE('CELL A1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL A1 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL A1 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL B1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL B1 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL B1 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL B2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL B2 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL B2 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL C1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C1 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL C1 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL C2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C2 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL C2 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL C3 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL C4 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL C5 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL C6 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C6 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL C6 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL C7 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL C7 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL C7 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL D1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL D1 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL D1 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL D2 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL D3 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL D4 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL D5 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL D6 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL D6 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL D6 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL E1 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL E2 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 BLUE',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL E3 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL E4 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL E4 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL E4 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL E4 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL E4 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL E4 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL E4 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL E5 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL E5 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL E5 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL E5 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL E5 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL E5 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL E5 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL F1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL F1 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL F1 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL F2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL F2 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL F2 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL F2 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL F2 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL F2 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL F2 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL F3 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL F3 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL F3 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL F3 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL F3 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL F3 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL F3 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL F4 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL F4 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL F4 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL F4 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL F4 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL F4 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL F4 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL F5 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL F5 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL F5 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL F5 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL F5 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL F5 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL F5 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL F6 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL F6 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL F6 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL G1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G1 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL G1 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL G2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G2 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL G2 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL G3 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G3 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL G3 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL G3 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL G3 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL G3 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL G3 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL G4 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G4 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL G4 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL G4 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL G4 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL G4 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL G4 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL G5 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G5 BLUE',state) > 0, 1, -1),
	IF(LOCATE('CELL G5 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL G5 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL G5 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL G5 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL G5 YELLOW',state) > 0, 1, -1), 
	IF(LOCATE('CELL G6 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G6 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL G6 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL G7 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL G7 GREEN',state) > 0, 1, -1), 
	IF(LOCATE('CELL G7 MAGENTA',state) > 0, 1, -1), 
	IF(LOCATE('CELL H1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL H1 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL H1 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL H2 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL H2 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL H2 TEAL',state) > 0, 1, -1), 
	IF(LOCATE('CELL I1 BLANK',state) > 0, 1, -1), 
	IF(LOCATE('CELL I1 RED',state) > 0, 1, -1), 
	IF(LOCATE('CELL I1 TEAL',state) > 0, 1, -1),
	LOCATE('NOOP',mo.move),
	LOCATE('(MOVE B1 A1)',mo.move),
	LOCATE('(MOVE B2 A1)',mo.move),
	LOCATE('(MOVE C3 A1)',mo.move),
	LOCATE('(MOVE C3 B1)',mo.move),
	LOCATE('(MOVE C4 B1)',mo.move),
	LOCATE('(MOVE C4 B2)',mo.move),
	LOCATE('(MOVE C5 A1)',mo.move),
	LOCATE('(MOVE C5 B2)',mo.move),
	LOCATE('(MOVE D2 B1)',mo.move),
	LOCATE('(MOVE D2 C3)',mo.move),
	LOCATE('(MOVE D3 B2)',mo.move),
	LOCATE('(MOVE D3 C3)',mo.move),
	LOCATE('(MOVE D3 C4)',mo.move),
	LOCATE('(MOVE D4 B1)',mo.move),
	LOCATE('(MOVE D4 C4)',mo.move),
	LOCATE('(MOVE D4 C5)',mo.move),
	LOCATE('(MOVE D5 B2)',mo.move),
	LOCATE('(MOVE D5 C5)',mo.move),
	LOCATE('(MOVE E1 A1)',mo.move),
	LOCATE('(MOVE E1 C3)',mo.move),
	LOCATE('(MOVE E1 D2)',mo.move),
	LOCATE('(MOVE E2 C4)',mo.move),
	LOCATE('(MOVE E2 D2)',mo.move),
	LOCATE('(MOVE E2 D3)',mo.move),
	LOCATE('(MOVE E3 A1)',mo.move),
	LOCATE('(MOVE E3 C3)',mo.move),
	LOCATE('(MOVE E3 C5)',mo.move),
	LOCATE('(MOVE E3 D3)',mo.move),
	LOCATE('(MOVE E3 D4)',mo.move),
	LOCATE('(MOVE E4 C4)',mo.move),
	LOCATE('(MOVE E4 D4)',mo.move),
	LOCATE('(MOVE E4 D5)',mo.move),
	LOCATE('(MOVE E5 A1)',mo.move),
	LOCATE('(MOVE E5 C5)',mo.move),
	LOCATE('(MOVE E5 D5)',mo.move),
	LOCATE('(MOVE F2 B2)',mo.move),
	LOCATE('(MOVE F2 D3)',mo.move),
	LOCATE('(MOVE F2 E1)',mo.move),
	LOCATE('(MOVE F2 E2)',mo.move),
	LOCATE('(MOVE F3 B1)',mo.move),
	LOCATE('(MOVE F3 D2)',mo.move),
	LOCATE('(MOVE F3 D4)',mo.move),
	LOCATE('(MOVE F3 E2)',mo.move),
	LOCATE('(MOVE F3 E3)',mo.move),
	LOCATE('(MOVE F4 B2)',mo.move),
	LOCATE('(MOVE F4 D3)',mo.move),
	LOCATE('(MOVE F4 D5)',mo.move),
	LOCATE('(MOVE F4 E3)',mo.move),
	LOCATE('(MOVE F4 E4)',mo.move),
	LOCATE('(MOVE F5 B1)',mo.move),
	LOCATE('(MOVE F5 D4)',mo.move),
	LOCATE('(MOVE F5 E4)',mo.move),
	LOCATE('(MOVE F5 E5)',mo.move),
	LOCATE('(MOVE G3 C3)',mo.move),
	LOCATE('(MOVE G3 C5)',mo.move),
	LOCATE('(MOVE G3 E1)',mo.move),
	LOCATE('(MOVE G3 E3)',mo.move),
	LOCATE('(MOVE G3 F2)',mo.move),
	LOCATE('(MOVE G3 F3)',mo.move),
	LOCATE('(MOVE G4 C4)',mo.move),
	LOCATE('(MOVE G4 E2)',mo.move),
	LOCATE('(MOVE G4 E4)',mo.move),
	LOCATE('(MOVE G4 F3)',mo.move),
	LOCATE('(MOVE G4 F4)',mo.move),
	LOCATE('(MOVE G5 C3)',mo.move),
	LOCATE('(MOVE G5 C5)',mo.move),
	LOCATE('(MOVE G5 E3)',mo.move),
	LOCATE('(MOVE G5 E5)',mo.move),
	LOCATE('(MOVE G5 F4)',mo.move),
	LOCATE('(MOVE G5 F5)',mo.move),
	LOCATE('(MOVE H1 D3)',mo.move),
	LOCATE('(MOVE H1 D5)',mo.move),
	LOCATE('(MOVE H1 F2)',mo.move),
	LOCATE('(MOVE H1 F4)',mo.move),
	LOCATE('(MOVE H1 G3)',mo.move),
	LOCATE('(MOVE H1 G4)',mo.move),
	LOCATE('(MOVE H2 D2)',mo.move),
	LOCATE('(MOVE H2 D4)',mo.move),
	LOCATE('(MOVE H2 F3)',mo.move),
	LOCATE('(MOVE H2 F5)',mo.move),
	LOCATE('(MOVE H2 G4)',mo.move),
	LOCATE('(MOVE H2 G5)',mo.move),
	LOCATE('(MOVE I1 E1)',mo.move),
	LOCATE('(MOVE I1 E3)',mo.move),
	LOCATE('(MOVE I1 E5)',mo.move),
	LOCATE('(MOVE I1 G3)',mo.move),
	LOCATE('(MOVE I1 G5)',mo.move),
	LOCATE('(MOVE I1 H1)',mo.move),
	LOCATE('(MOVE I1 H2)',mo.move)
FROM 
    states s, 
    matches m, 
    match_players p,
    moves mo
where 
    m.match_id = s.match_id and
    p.match_id = m.match_id and
    p.match_id = m.match_id and
    p.roleindex = mo.roleindex and
    mo.roleindex = p.roleindex and
    mo.match_id = m.match_id and
    mo.step_number = s.step_number and

    m.game = 'chinesecheckers6' and 
    p.player != 'Random' and
    mo.move != 'NOOP' and
    p.roleindex = 3
INTO OUTFILE 'chinese_checkers_6_role3_noNoop.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';